window:
  title: Alacritty

  class:
    instance: Alacritty


scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: monospace
  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

  size: 14.0


visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

background_opacity: 1

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

dynamic_title: true

cursor:
  style: Block
  vi_mode_style: Block
  unfocused_hollow: false

live_config_reload: true

shell:
  program: /run/current-system/sw/bin/zsh

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false

  url:
    launcher:
      program: xdg-open
      args: []
    modifiers: None

key_bindings:
  - { key: V,         mods: Alt,                  action: Paste               }
  - { key: C,         mods: Alt,                  action: Copy                }

  - { key: Key0,     mods: Control,                 action: ResetFontSize     }
  - { key: Equals,   mods: Control,                 action: IncreaseFontSize  }
  - { key: Add,      mods: Control,                 action: IncreaseFontSize  }
  - { key: Subtract, mods: Control,                 action: DecreaseFontSize  }
  - { key: Minus,    mods: Control,                 action: DecreaseFontSize  }

  # Vi Mode
  # - { key: V,  mods: Shift|Alt, mode: Vi, action: ScrollToBottom              }
  # - { key: V,  mods: Shift|Alt,           action: ToggleViMode                }


colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  cursor:
    text: '0x2E3440'
    cursor: '0xD8DEE9'
  normal:
    black: '0x3B4252'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x88C0D0'
    white: '0xE5E9F0'
  bright:
    black: '0x4C566A'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x8FBCBB'
    white: '0xECEFF4'
