#!/usr/bin/env sh

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config window_gap 0

bspc config normal_border_color "#3b4252"
bspc config active_border_color "#3b4252"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"

# Extra padding for polybar
bspc config -m primary top_padding 24
bspc config -m primary top_padding 24
