imports = [
  "git.hooks"
]

[devshell]
packages = [
  "nixpkgs-fmt"
]

[[commands]]
package = "treefmt"

[git.hooks]
enable = true
pre-commit.text = """\
set -euo pipefail

treefmt --fail-on-change
"""
