[kanidm]
src.github = "kanidm/kanidm"
fetch.github = "kanidm/kanidm"

[authelia]
src.github = "authelia/authelia"
fetch.github = "authelia/authelia"

[authelia-web]
src.github = "authelia/authelia"
fetch.tarball = "https://github.com/authelia/authelia/releases/download/$ver/authelia-$ver-public_html.tar.gz"

[tailscale]
src.github = "tailscale/tailscale"
fetch.github = "tailscale/tailscale"

[dymoprint]
src.pypi = "dymoprint"
fetch.pypi = "dymoprint"

[tproxy]
src.github = "kevwan/tproxy"
fetch.github = "kevwan/tproxy"
