file = "vimPlugins/default.nix"

[plenary-nvim]
repo = "nvim-lua/plenary.nvim"

[impatient-nvim]
repo = "lewis6991/impatient.nvim"

[catppuccin-nvim]
repo = "catppuccin/nvim"

[nvim-lspconfig]
repo = "neovim/nvim-lspconfig"

[lsp-zero-nvim]
repo = "VonHeikemen/lsp-zero.nvim"

[nvim-cmp]
repo = "hrsh7th/nvim-cmp"

[cmp-path]
repo = "hrsh7th/cmp-path"

[cmp-buffer]
repo = "hrsh7th/cmp-buffer"

[cmp-nvim-lua]
repo = "hrsh7th/cmp-nvim-lua"

[cmp-nvim-lsp]
repo = "hrsh7th/cmp-nvim-lsp"

[null-ls-nvim]
repo = "jose-elias-alvarez/null-ls.nvim"

[vim-illuminate]
repo = "RRethy/vim-illuminate"

[rust-tools-nvim]
repo = "simrat39/rust-tools.nvim"

[nvim-treesitter]
repo = "nvim-treesitter/nvim-treesitter"

[nvim-ts-context-commentstring]
repo = "JoosepAlviste/nvim-ts-context-commentstring"

[nvim-ts-autotag]
repo = "windwp/nvim-ts-autotag"

[todo-comments-nvim]
repo = "folke/todo-comments.nvim"

[nvim-web-devicons]
repo = "nvim-tree/nvim-web-devicons"

[nvim-tree-lua]
repo = "nvim-tree/nvim-tree.lua"

[vim-bbye]
repo = "moll/vim-bbye"

[telescope-nvim]
repo = "nvim-telescope/telescope.nvim"

[gitsigns-nvim]
repo = "lewis6991/gitsigns.nvim"

[nvim-autopairs]
repo = "windwp/nvim-autopairs"

[comment-nvim]
repo = "numToStr/Comment.nvim"

[bufferline-nvim]
repo = "akinsho/bufferline.nvim"

[lualine-nvim]
repo = "nvim-lualine/lualine.nvim"

[indent-blankline-nvim]
repo = "lukas-reineke/indent-blankline.nvim"

[base64-nvim]
repo = "moevis/base64.nvim"

[dressing-nvim]
repo = "stevearc/dressing.nvim"

[copilot-lua]
repo = "zbirenbaum/copilot.lua"

[copilot-cmp]
repo = "zbirenbaum/copilot-cmp"

[lua-snip]
repo = "L3MON4D3/LuaSnip"

[cmp-luasnip]
repo = "saadparwaiz1/cmp_luasnip"

[nvim-notify]
repo = "rcarriga/nvim-notify"

[move-nvim]
repo = "fedepujol/move.nvim"
