add_newline = true

[character]
success_symbol = "[λ ›](bold green)"
error_symbol = "[λ ›](bold red)"
vicmd_symbol = "[λ ·](bold green)"

[cmd_duration]
show_notifications = true
min_time = 300_000
min_time_to_notify = 300_000
