#!/bin/sh

# Remove all old rules
bpsc rule -r "*"

### Autostart programs

sxhkd -c ~/.config/bspwm/sxhkdrc &
feh --bg-fill ~/.config/wallpaper.png
xrandr --output DP-3 --auto --left-of HDMI-0
~/.config/polybar/launch.sh

### Configure monitor workspaces

bspc monitor HDMI-0 -s DP-3
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-3 -d 6 7 8 9 10

### General settings

bspc config focused_border_color "#81a1c1"
bspc config normal_border_color "#4c566a"

bspc config border_width 3
bspc config window_gap 15
bspc config top_padding 24
bspc config bottom_padding 8
bspc config focus_follows_pointer true

### Load Xresources
xrdb ~/.Xresources

