#!/bin/sh

# Remove all old rules
bpsc rule -r "*"

### Autostart programs

sxhkd -c ~/.config/bspwm/sxhkdrc &
xrandr --output DP-3 --auto --left-of HDMI-0

### Configure monitor workspaces

bspc monitor HDMI-0 -s DP-3
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-3 -d 6 7 8 9 10

### General settings

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer true

bspc config border_width 3
bspc config window_gap 15
bspc config bottom_padding 8

bspc rule -a Pinentry state=floating center=on

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
