#!/usr/bin/env bash
set -Eeuo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h]

Makes a connected camera availabe as a webcam.

Available options:
  -h, --help      Print this help and exit.
EOF

  exit
}

parse_flags() {
  while :; do
    case "${1-}" in
    -h | --help) usage ;;
    *) break ;;
    esac
    shift
  done

  return 0
}

parse_flags "$@"

gphoto2 --stdout --capture-movie | \
  ffmpeg \
    -i - \
    -vcodec rawvideo \
    -pix_fmt yuv420p \
    -threads 0 \
    -f v4l2 /dev/video0
