[
  ./core
  ./graphical
  ./graphical/x11.nix
  ./graphical/sway.nix
  ./graphical/bspwm.nix
  ./network/networkmanager.nix
  ./network/vpn.nix
  ./laptop.nix
  ./virt.nix
  ./sshd.nix
  ./yubikey.nix
]
