#!/usr/bin/env bash

dir="/tmp/mako"
mkdir -p $dir

tmp="$dir/history.json"
lock="$dir/toggle.lock"
lockinfo="$dir/lock-info"

touch $lockinfo

declare ids
export toggle_icon=""

get_ids() {
  mapfile -t ids < <(makoctl history | gojq -r ".data[] | .[] | select(.appname.data != \"Spotify\") | .id.data")
}

get_notif() {
  echo -n '['

  for id in "${ids[@]}"; do
      mapfile -t n < <(gojq -r ".data[] | .[] | select(.id.data == $id) | .\"app-name\".data, .summary.data, .body.data" "$tmp" | sed -r '/^\s*$/d' | sed -e 's/\%/ percent/g')
      echo -n ''$([ $id -eq ${ids[0]} ] || echo ,)' { '
      echo -n '"id": "'"$id"'", "appname": "'"${n[0]}"'", "summary": "'"${n[1]}"'", "body": "'"${n[2]}"'"'
      echo -n '}' 
  done

  echo ']'
}

toggle() {
  if [ ! -f "$lock" ]; then
    export toggle_icon=""
    makoctl mode -a do-not-disturb > /dev/null
    touch "$lock"
  else
    export toggle_icon=""
    makoctl mode -r do-not-disturb > /dev/null
    rm "$lock"
  fi

  echo "$toggle_icon" >> $lockinfo
}

clear() {
  true
  # pkill mako
  # echo "" >> $lockinfo
}

get_icon() {
  if [ ${#ids[@]} -eq 0 ]; then
    echo "󰆂"
  else
    echo "󰆄"
  fi
}

if [ "$1" == "toggle" ]; then
  toggle
  makoctl history > "$tmp"
elif [ "$1" == "refresh" ]; then
  makoctl history > "$tmp"
elif [ "$1" == "clear" ]; then
  clear
  makoctl history > "$tmp"
elif [ "$1" == "icons" ]; then
  makoctl history > "$tmp"
  get_ids
  tail -f "$lockinfo" | while read -r icon; do
    get_ids
    echo '{"toggle_icon": "'"$icon"'", "icon": "'"$(get_icon)"'"}'
  done
else
  makoctl history > "$tmp"
  get_ids
  get_notif
  tail -f "$tmp" 2>/dev/null | rg --line-buffered "aa\{sv\}" | while read -r; do
    get_ids
    get_notif
  done
fi
