# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  authelia = {
    pname = "authelia";
    version = "v4.38.8";
    src = fetchFromGitHub {
      owner = "authelia";
      repo = "authelia";
      rev = "v4.38.8";
      fetchSubmodules = false;
      sha256 = "sha256-wuGA3nxzMhpaJKPQeMgVv27zmLyUL5o3MVY+BM6SbAI=";
    };
  };
  authelia-web = {
    pname = "authelia-web";
    version = "v4.38.8";
    src = fetchTarball {
      url = "https://github.com/authelia/authelia/releases/download/v4.38.8/authelia-v4.38.8-public_html.tar.gz";
      sha256 = "sha256-0xcuWVNSBGnqxAf7QPVeuf2CBwtbvatrMm4UHl0zfCg=";
    };
  };
  dymoprint = {
    pname = "dymoprint";
    version = "2.5.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/d/dymoprint/dymoprint-2.5.0.tar.gz";
      sha256 = "sha256-mTa+W5trcOiz6tSRIMbVk2VD5BjQaJJMdGC5mpigckA=";
    };
  };
  kanidm = {
    pname = "kanidm";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "kanidm";
      repo = "kanidm";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-nDAHlpQefCbmz4jw/1cDGQWkfvn/vIqpsOCPjn6yQ6s=";
    };
  };
  pymodbus-repl = {
    pname = "pymodbus-repl";
    version = "2.0.3";
    src = fetchFromGitHub {
      owner = "pymodbus-dev";
      repo = "repl";
      rev = "2.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-yqSeuguzFE3cgP1VxpVI0e0dz0ja+ix0AS/nQPNLRMU=";
    };
  };
  qmodbus = {
    pname = "qmodbus";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "ed-chemnitz";
      repo = "qmodbus";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-mBwP5zZiMxNo8zKmcVo5XMREt2rQ8A0JtBN179Wf4pM=";
    };
  };
  tproxy = {
    pname = "tproxy";
    version = "v0.8.1";
    src = fetchFromGitHub {
      owner = "kevwan";
      repo = "tproxy";
      rev = "v0.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-LX3ciC3cMYuQPm6ekEkJPrSdTXH+WZ4flXyrsvJZgn8=";
    };
  };
}
