# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  authelia = {
    pname = "authelia";
    version = "v4.37.5";
    src = fetchFromGitHub {
      owner = "authelia";
      repo = "authelia";
      rev = "v4.37.5";
      fetchSubmodules = false;
      sha256 = "sha256-xsdBnyPHFIimhp2rcudWqvVR36WN4vBXbxRmvgqMcDw=";
    };
  };
  authelia-web = {
    pname = "authelia-web";
    version = "v4.37.5";
    src = fetchTarball {
      url = "https://github.com/authelia/authelia/releases/download/v4.37.5/authelia-v4.37.5-public_html.tar.gz";
      sha256 = "1sq90s0f5l7l0675jyaa6xm6kx0likdz0cc13kz86726sdq7vhhv";
    };
  };
  base64-nvim = {
    pname = "base64-nvim";
    version = "67fb5f12db252b3e2bd190250d3edbed7aa8d3aa";
    src = fetchFromGitHub {
      owner = "moevis";
      repo = "base64.nvim";
      rev = "67fb5f12db252b3e2bd190250d3edbed7aa8d3aa";
      fetchSubmodules = false;
      sha256 = "sha256-eByAH1iy7Px/AhtA6FzMPgP56TgaR0p+UumXrHmlbuU=";
    };
  };
  dressing-nvim = {
    pname = "dressing-nvim";
    version = "5f44f829481640be0f96759c965ae22a3bcaf7ce";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "5f44f829481640be0f96759c965ae22a3bcaf7ce";
      fetchSubmodules = false;
      sha256 = "sha256-89HwP+zxMN5CPPN3dd3yMfCB07mtBhv6lcWuEWnedfw=";
    };
  };
  kanidm = {
    pname = "kanidm";
    version = "v1.1.0-alpha.11";
    src = fetchFromGitHub {
      owner = "kanidm";
      repo = "kanidm";
      rev = "v1.1.0-alpha.11";
      fetchSubmodules = false;
      sha256 = "sha256-TVGLL1Ir/Nld0kdhWmcYYmChrW42ctJPY/U7wtuEwCo=";
    };
  };
  lsp-zero-nvim = {
    pname = "lsp-zero-nvim";
    version = "5b68fbdc91102de41fb53da79f52752370d71a7e";
    src = fetchFromGitHub {
      owner = "VonHeikemen";
      repo = "lsp-zero.nvim";
      rev = "5b68fbdc91102de41fb53da79f52752370d71a7e";
      fetchSubmodules = false;
      sha256 = "sha256-OCnwzEIdzSkwITiD3NqF+CgKKt7wOHrIu4Hx06ag218=";
    };
  };
  tabnine-nvim = {
    pname = "tabnine-nvim";
    version = "0816b5f06755927f4af8391b2957488153a70796";
    src = fetchFromGitHub {
      owner = "codota";
      repo = "tabnine-nvim";
      rev = "0816b5f06755927f4af8391b2957488153a70796";
      fetchSubmodules = true;
      sha256 = "sha256-jpVAE4Yc6VYMrmDTgagQ157exb/T+ouBxMevTDZnvxo=";
    };
  };
}
