#!/usr/bin/env bash
set -euo pipefail

cache_dir="$HOME/.cache/comma"

if [[ $# -lt 1 ]]; then
  >&2 echo "usage: , <program> [arguments]"
  exit 1
fi

if [[ "$1" == "--install" ]] || [[ "$1" == "-i" ]]; then
  install=1
  shift
else
  install=""
fi

if [[ "$1" == "--search" ]] || [[ "$1" == "-s" ]]; then
  search=1
  shift
else
  search=""
fi

argv0=$1; shift

if [[ -f "${cache_dir}/${argv0}" && ! -n $search ]]; then
  attr="$(cat ${cache_dir}/${argv0})"
else
  case "${argv0}" in
    @OVERLAY_PACKAGES@)
      attr="${argv0}"
      ;;
    *)
      attr="$(nix-locate --db "${NIX_INDEX_DB}" --top-level --minimal --at-root --whole-name "/bin/${argv0}")"
      if [[ "$(echo "${attr}" | wc -l)" -ne 1 ]]; then
        attr="$(echo "${attr}" | fzf)"
      fi
      ;;
  esac
fi

if [[ -z $attr ]]; then
  >&2 echo "no match"
  exit 1
fi

if [[ ! -f "${cache_dir}/${argv0}" ]]; then
  mkdir -p "${cache_dir}"
  echo "${attr}" >> "${cache_dir}/${argv0}"
fi

if [[ -n $install ]]; then
  nix profile install "nixpkgs#${attr%%.*}"
elif [[ -n $search ]]; then
  echo $attr
else
  nix shell "nixpkgs#${attr}" -c "${argv0}" "$@"
fi
