name: "Check & Cachix"
on:
  push:
    branches:
      - new
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          substituters = https://stx.cachix.org https://nix-community.cachix.org https://cache.nixos.org
          trusted-public-keys = stx.cachix.org-1:mCLmdjTaKn3704lctpvqOgc0uvmu0NnIUP3/d5g2aZ0= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: stx
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix -Lv flake check
    - run: nix -Lv build ".#nixosConfigurations.NixOS.config.system.build.toplevel"
    - run: nix -Lv develop -c echo OK
    - run: nix -Lv develop -c bud --help
